export const profileFormFields = [
  {
    name: "full_name",
    label: "Name",
    type: "text",
  },
  {
    name: "headline",
    label: "Headline",
    type: "text",
  },
  {
    name: "email",
    label: "Email",
    type: "email",
  },
  {
    name: "phone",
    label: "Mobile",
    type: "number",
  },
  {
    name: "companyName",
    label: "Company Name",
    type: "text",
    placeholder: "Add your company name",
  },
  {
    name: "profession",
    label: "Profession",
    type: "button",
    placeholder: "Select your profession",
  },
  {
    name: "gstin",
    label: "GST Number",
    type: "text",
    placeholder: "",
  },
  {
    name: "bio",
    label: "Bio",
    type: "text",
    placeholder: "Tell us a bit about yourself",
  },
  {
    name: "city",
    label: "City",
    type: "text",
    placeholder: "eg. Bengaluru",
  },
  {
    name: "state",
    label: "State",
    type: "text",
    placeholder: "eg. Karnataka",
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    placeholder: "eg. India",
  },
  {
    name: "zip_code",
    label: "Zip Code",
    type: "number",
  },
  {
    name: "website",
    label: "Website",
    type: "url",
    placeholder: "Add your website",
  },
  {
    name: "youtube_url",
    label: "YouTube URL",
    type: "url",
    placeholder: "Add your YouTube URL",
  },
  {
    name: "linkedin_url",
    label: "Linkedin URL",
    type: "url",
    placeholder: "Add your Linkedin Profile",
  },
  {
    name: "facebook_url",
    label: "Facebook URL",
    type: "url",
    placeholder: "Add your Facebook Profile",
  },
  {
    name: "whatsapp_link",
    label: "WhatsApp Link",
    type: "url",
    placeholder: "http://wa.me/918000000000",
  },
  {
    name: "instagram_url",
    label: "Instagram URL",
    type: "url",
    placeholder: "Add your Instagram Profile",
  },
];
