import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import { googleIcon,facebookIcon, loginBg} from "theme/icon";
// import "react-phone-input-2/lib/bootstrap.css";


export default function Login() {
  const router = useRouter();

  const [activeTab, setActiveTab] = React.useState(0);
  const [phone, setPhone] = React.useState("");

  const handleTabChange = (index) => {
    setActiveTab(index);
  };

  <div className="social">
  <a src={googleIcon} alt="Google Icon" />
</div>

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />

        <title>Login | pwip - Export Costing </title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-screen p">
        <div className=" w-auto h-56 bg-[#194969] ">
          <div className="text-white text-2xl">
          <h1>ACCOUNT LOGIN</h1>
          </div>
        </div>
        <div className="h-full bg-[#ffffff] w-full inline-flex flex-col space-y-8 relative mt-10 px-8">
          <div className="w-full inline-flex flex-col space-y-8 relative ">
           <div className="w=full inline-flex flex-col space-y-3 relative">
             <div className="mt-2">
             <input id="email" name="email" type="email" autocomplete="email" required class="block w-full rounded border-0 px-4 py-3 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
             <label for="floating_outlined" className="absolute text-xs text-[#4F5655] text-900 -translate-y-2 scale-75 top-2  z-10 origin-[0] bg-white px-1 left-2">Email</label>
            </div>
          </div>
        </div>
        <button
              onClick={() => router.push("export-costing")}
              className="w-full rounded py-3 px-4 bg-[#003559] text-white text-center text-md font-semibold"
            >
              Log in
            </button>

            <div class="relative flex items-center">
             <div class="flex-grow border-t border-gray-400"></div>
             <span class="flex-shrink mx-4 text-gray-400">or login with</span>
             <div class="flex-grow border-t border-gray-400"></div>
           </div>

           <div className="flex flex-row items-center pt-7 justify-center">
            <span className="pr-6  ">{googleIcon}</span>
            <span className="pl-6  ">{facebookIcon}</span>
           </div>
         
        
          <div className="pt-48 bottom-0 left-0 right-0 flex justify-center ">
           <span className="line-clamp-1 font-regular text-[#77787b] text-md" >
             Don't have an account? {" "}
             <span onClick={() => router.push("signup")} className="text-[#0B7764] cursor-pointer">Register now</span>
           </span>
          </div>
        

      </div>
</div>

    </React.Fragment>
  );
}
