import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import { useOverlayContext } from "@/context/OverlayContext";

import AppLayout from "@/layouts/appLayout.jsx";

// Import Components
import { Header } from "@/components/Header";
import { Button } from "@/components/Button";

import { chevronDown, plusIcon, minusIcon } from "../../../../theme/icon";

// Import Containers
import SelectVariantContainer from "@/containers/ec/SelectVariant";
import SelectLocationContainer from "@/containers/ec/SelectLocation";
import SelectBagsContainer from "@/containers/ec/SelectBags";
import SelectCargoContainersContainer from "@/containers/ec/SelectContainers";

// Import Layouts

export default function EditCosting() {
  const router = useRouter();

  const { openBottomSheet } = useOverlayContext();
  const [mainContainerHeight, setMainContainerHeight] = React.useState(0);
  const [activeTab, setActiveTab] = React.useState(0);

  React.useEffect(() => {
    const element = document.getElementById("fixedMenuSection");
    if (element) {
      const height = element.offsetHeight;
      setMainContainerHeight(height);
    }
  }, []);

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />
        {/* <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        /> */}

        <title>Export Costing by pwip</title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Header />

        <div
          id="fixedMenuSection"
          className="fixed top-[92px] h-[auto] w-full bg-pwip-gray-45 z-10 py-5 px-5"
        >
          <div className="w-full h-[46px] bg-pwip-gray-300 rounded-full inline-flex items-center p-1">
            <div
              onClick={() => setActiveTab(0)}
              className={`w-[50%] h-full inline-flex items-center justify-center ${
                activeTab === 0 ? "bg-white" : "opacity-40"
              } rounded-full`}
            >
              <span className="text-pwip-gray-1100 font-sans font-bold text-sm">
                Costing
              </span>
            </div>

            <div
              onClick={() => setActiveTab(1)}
              className={`w-[50%] h-full inline-flex items-center justify-center ${
                activeTab === 1 ? "bg-white" : "opacity-40"
              } rounded-full`}
            >
              <span className="text-pwip-gray-1100 font-sans font-bold text-sm">
                Breakup
              </span>
            </div>
          </div>
        </div>

        <div
          className={`min-h-screen h-full w-full bg-pwip-gray-45 pb-[32px] overflow-auto px-5 hide-scroll-bar`}
          style={{
            paddingTop: mainContainerHeight + 92 + "px",
          }}
        >
          <div className="inline-flex flex-col w-full space-y-4">
            <div className="inline-flex flex-col w-full">
              <label className="text-sm font-normal text-pwip-gray-600">
                Costing Name
              </label>
              <input
                placeholder="Ex: Sona Masuri"
                type="text"
                className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
              />
            </div>

            <div className="inline-flex flex-col w-full">
              <label className="text-sm font-normal text-pwip-gray-600">
                Rice Name
              </label>
              <div className="inline-flex items-center relative">
                <input
                  placeholder="Ex: Sona masuri"
                  type="text"
                  onClick={() => {
                    const content = (
                      <div>
                        <SelectVariantContainer
                          roundedTop={false}
                          noTop={true}
                          noPaddingBottom={true}
                        />
                      </div>
                    );
                    openBottomSheet(content);
                  }}
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
                <div className="absolute h-full mt-[4px] inline-flex items-center right-[18px]">
                  {chevronDown}
                </div>
              </div>
            </div>

            <div className="inline-flex flex-col w-full">
              <label className="text-sm font-normal text-pwip-gray-600">
                Rice Name
              </label>
              <div className="inline-flex items-center relative h-[40px] mt-[4px]  w-full border-[1px] border-pwip-gray-650 rounded-md bg-white">
                <div className="w-[44px] h-full inline-flex items-center justify-center right-[18px] bg-white border-r-[1px] border-r-pwip-gray-650 rounded-l-md text-pwip-gray-400">
                  {minusIcon}
                </div>
                <input
                  placeholder="Ex: 10%"
                  type="text"
                  className="inline-flex items-center w-full px-[18px] text-xs font-sans text-center"
                />
                <div className="w-[44px] h-full inline-flex items-center justify-center right-[18px] bg-white border-l-[1px] border-l-pwip-gray-650 rounded-r-md text-pwip-gray-400">
                  {plusIcon}
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="inline-flex flex-col w-full">
                <label className="text-sm font-normal text-pwip-gray-600">
                  Bag type
                </label>
                <div className="inline-flex items-center relative">
                  <input
                    placeholder="Ex: PP Woven"
                    type="text"
                    onClick={() => {
                      const content = (
                        <div>
                          <SelectBagsContainer
                            roundedTop={false}
                            noTop={true}
                            noPaddingBottom={true}
                          />
                        </div>
                      );
                      openBottomSheet(content);
                    }}
                    className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                  />
                  <div className="absolute h-full mt-[4px] inline-flex items-center right-[18px]">
                    {chevronDown}
                  </div>
                </div>
              </div>

              <div className="inline-flex flex-col w-full">
                <label className="text-sm font-normal text-pwip-gray-600">
                  Bag size
                </label>
                <input
                  placeholder="Ex: 5 kg"
                  type="text"
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
              </div>
            </div>

            <div className="inline-flex flex-col w-full">
              <label className="text-sm font-normal text-pwip-gray-600">
                Select port of orgin
              </label>
              <div className="inline-flex items-center relative">
                <input
                  placeholder="Ex: Mumbai india"
                  type="text"
                  onClick={() => {
                    const content = (
                      <div>
                        <SelectLocationContainer
                          title="Select Port of Origin"
                          roundedTop={false}
                          noTop={true}
                          noPaddingBottom={true}
                        />
                      </div>
                    );
                    openBottomSheet(content);
                  }}
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
                <div className="absolute h-full mt-[4px] inline-flex items-center right-[18px]">
                  {chevronDown}
                </div>
              </div>
            </div>

            <div className="inline-flex flex-col w-full">
              <label className="text-sm font-normal text-pwip-gray-600">
                Select port of destination
              </label>
              <div className="inline-flex items-center relative">
                <input
                  placeholder="Ex: Mumbai india"
                  type="text"
                  onClick={() => {
                    const content = (
                      <div>
                        <SelectLocationContainer
                          title="Select Port of Destination"
                          roundedTop={false}
                          noTop={true}
                          noPaddingBottom={true}
                        />
                      </div>
                    );
                    openBottomSheet(content);
                  }}
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
                <div className="absolute h-full mt-[4px] inline-flex items-center right-[18px]">
                  {chevronDown}
                </div>
              </div>
            </div>

            <div className="inline-flex flex-col w-full">
              <label className="text-sm font-normal text-pwip-gray-600">
                Container type
              </label>
              <div className="inline-flex items-center relative">
                <input
                  placeholder="Ex: Mumbai india"
                  type="text"
                  onClick={() => {
                    const content = (
                      <div>
                        <SelectCargoContainersContainer
                          roundedTop={false}
                          noTop={true}
                          noPaddingBottom={true}
                        />
                      </div>
                    );
                    openBottomSheet(content);
                  }}
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
                <div className="absolute h-full mt-[4px] inline-flex items-center right-[18px]">
                  {chevronDown}
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="inline-flex flex-col w-full">
                <label className="text-sm font-normal text-pwip-gray-600">
                  No of containers
                </label>
                <input
                  placeholder="Ex: 10"
                  type="text"
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
              </div>

              <div className="inline-flex flex-col w-full">
                <label className="text-sm font-normal text-pwip-gray-600">
                  Containers weight
                </label>
                <input
                  placeholder="Ex: 1000 kg"
                  type="text"
                  className="inline-flex items-center h-[40px] mt-[4px] w-full rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
              </div>
            </div>

            <div className="!mt-10 inline-flex flex-col w-full space-y-10">
              <div className="inline-flex items-center space-x-4 w-full">
                <input
                  type="checkbox"
                  className="inline-flex items-center h-[20px] w-[20px] rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
                <label className="text-sm font-normal text-pwip-gray-600">
                  20% Export duty
                </label>
              </div>

              <div className="inline-flex items-center space-x-4 w-full">
                <input
                  type="checkbox"
                  className="inline-flex items-center h-[20px] w-[20px] rounded-md bg-white border-[1px] border-pwip-gray-650 px-[18px] text-xs font-sans"
                />
                <label className="text-sm font-normal text-pwip-gray-600">
                  Full fill through PWIP
                </label>
              </div>
            </div>

            <div className="w-full !mt-[32px]">
              <Button
                type="primary"
                label="Update consting"
                // onClick={() => {
                //   router.push("/export-costing/costing");
                // }}
              />
            </div>
          </div>
        </div>
      </AppLayout>
    </React.Fragment>
  );
}
