/** @format */

import React from "react";
import Head from "next/head";

import withAuth from "@/hoc/withAuth";
import AppLayout from "@/layouts/appLayout.jsx";
import SubscriptionDetailCard from "@/components/SubscriptionDetailCard";

// Import Components
import { Header } from "@/components/Header";

function SubscriptionDetails() {
  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />

        <title>Subscription | PWIP</title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />

        <meta name="apple-mobile-web-app-status-bar-style" content="default" />

        {/* <link rel="manifest" href="/manifest.json" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <AppLayout>
        <Header />

        <div className={`relative h-full w-full bg-white z-0`}>
          <div
            className={`min-h-[calc(100vh-120px)] inline-flex  bg-pwip-v2-primary-100 flex-col h-full w-full px-5 pt-[82px] pb-[120px] overflow-auto hide-scroll-bar`}
          >
            <React.Fragment>
              <SubscriptionDetailCard />
            </React.Fragment>
          </div>
        </div>
        {/*  */}
      </AppLayout>
    </React.Fragment>
  );
}

export default withAuth(SubscriptionDetails);
