import React, {useState, useEffect, useRef} from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { useFormik } from "formik";

import withAuth from "@/hoc/withAuth";
import { useOverlayContext } from "@/context/OverlayContext";
import { cameraIcon } from "../../../theme/icon";
import { profileFormFields } from "@/constants/profileFormFields";
import { professionOptions } from "@/constants/professionOptions";
import {
  fetchProfileFailure,
  saveProfileRequest,
  saveProfileFailure,
  updateProfileRequest,
  fetchProfileRequest,
  updateProfileFailure,
} from "../../../redux/actions/profileEdit.actions";

// Import Components
import { Header } from "@/components/Header";

const initialValues = {
  name: "",
  email: "",
  mobile: "",
  companyName: "",
  profession: "",
  gstNumber: "",
}

const onSubmit= values => {
  console.log('Form Payload', values)
}

const validate= values => {
  let errors ={}
    if (!values.name){
      errors.name='required'
    }
    if (!values.email){
      errors.email='required'
    } else if(!/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\b/i.test(values.email)){
      errors.email='Invalid Email'
    }
    if (!values.mobile){
      errors.mobile='required'
    } else if (!/^\d{10}$/i.test(values.mobile)) {
      errors.mobile = 'Mobile number must be 10 digits';
    }
  return errors
}

function ProfileEdit() {
  const router = useRouter();
  const { data: session } = useSession();

  const [mainContainerHeight, setMainContainerHeight] = useState(0);
  const [userData, setUserData] = React.useState(null);

  const formFields = [...profileFormFields];
  const professionList = [...professionOptions];

  const formik = useFormik({
    initialValues,
    onSubmit,
    validate,
  });

  useEffect(() => {
    if (session) {
      setUserData(session?.user);
      formik.setValues({
        ...formik.values,
        name: session.user.name,
        email: session.user.email,
      });
    }  
  }, [session]);

  const {
    openBottomSheet,
    closeBottomSheet,
    openToastMessage,
    closeToastMessage,
  } = useOverlayContext();

  const handleProfessionSelect = (value) => {
    formik.setFieldValue("profession", value);
    closeBottomSheet();
  };

  const handleProfessionBottomSheet = () => {
    const content = (
      <React.Fragment>
        <div className="px-5 mb-6 pt-4">
          <span className="text-base font-sans font-semibold text-pwip-gray-900 text-left">
            Select Profession
          </span>
        </div>

        <div className=" px-5 pb-[4rem] grid grid-cols-2 gap-4">
          {[...professionList].map((item, index) => {
            return (
              <div
                key={item.value + index}
                className="h-40 w-40 rounded-md bg-pwip-white inline-flex flex-col space-t"
                style={{
                  boxShadow:
                    "0px 3px 6px -4px rgba(0, 0, 0, 0.12), 0px 6px 16px 0px rgba(0, 0, 0, 0.08), 0px 9px 28px 8px rgba(0, 0, 0, 0.05)",
                }}
                onClick={() => handleProfessionSelect(item.value)}
              >
                <div className="w-full pt-3 inline-flex items-center justify-center">
                  <img src={item.image} />
                </div>
                <div className=" flex w-fill flex-col space-y-[3px]">
                  <span className="text-pwip-gray-700 text-sm font-bold font-sans line-clamp-1 text-center">
                    {item.label}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </React.Fragment>
    );
    openBottomSheet(content);
  };
    
  const handleFormSubmit = async (values) => {
    try {
      console.log("clicked submit")
      console.log('custom submit fn', values)
      openToastMessage("Update successful!", "success");
    } catch (error) {
      console.error("Update failed:", error);
      openToastMessage("Update failed. Please try again.", "error");
    }
  };

  React.useEffect(() => {
    const element = document.getElementById("fixedMenuSection");
    if (element) {
      const height = element.offsetHeight;
      setMainContainerHeight(height);
    }
  }, []);

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />

        <title>Export Costing by pwip</title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <div
          id="fixedMenuSection"
          className={`h-[auto] fixed mt-[68px] w-full bg-pwip-primary z-10 px-5`}
        >
          <div className="inline-flex items-center space-x-5">
          <div className="h-[134px] w-[134px] rounded-full ring-1 ring-white ml-[7rem] p-[2px] relative top-2 z-20">
          <div className="absolute inset-0 flex items-center justify-center">
          {cameraIcon}
          </div>
         <img
            src={userData?.picture || "/assets/images/no-profile.png"}
           className="h-full w-full rounded-full object-cover"
          />
        </div>
          </div>
          <div className="absolute bottom-[-16px] left-0 bg-pwip-white-100 h-[5rem] w-full rounded-t-2xl z-10" />
        </div>
        <div
          className={`min-h-screen inline-flex flex-col w-full bg-pwip-white-100 overflow-auto px-5 hide-scroll-bar relative`}
          style={{
            paddingTop: mainContainerHeight * 1.7 + "px",
            paddingBottom: mainContainerHeight - 52 + "px",
          }}
        >
            <span className="text-pwip-gray-100 w-full font-sans font-normal text-lg text-left">
            Personal details
          </span>
              <form onSubmit={(e) => {
                    e.preventDefault(); 
                    formik.handleSubmit();
                    handleFormSubmit(formik.values);
        }}>
                {formFields.map((field) => (
                <div key={field.name} className="relative mb-4">
                <input
                  type={field.type}
                  id={field.name}
                  name={field.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  maxLength={field.name === "mobile" ? 10 : undefined}
                  value={formik.values[field.name]}
                  style={{ textAlign: 'left' }}
                  className={`block px-2.5 pb-3 pt-3 my-6 w-full text-sm text-gray-900 bg-transparent rounded-sm border ${
                    formik.errors[field.name]  && formik.touched[field.name]
                      ? 'border-red-300' // Apply red border when there's an error
                      : 'border-pwip-gray-300'
                  } appearance-none focus:outline-none focus:ring-0 focus:border-pwip-primary peer`}
                  placeholder=""
                  onClick={() => {
                    if (field.name === "profession") {
                      handleProfessionBottomSheet();
                    }
                  }}
                />
                {formik.errors[field.name] && formik.touched[field.name] ? (
                  <p 
                  className="absolute text-red-400 text-xs"
                  style={{ top: '100%'}} 
                  >{formik.errors[field.name]}</p>
                ) : null}
                <label
                  htmlFor={field.name}
                  className="absolute text-sm text-pwip-gray-600 -top-2 left-3 bg-pwip-white-100 focus:text-pwip-primary px-2 font font-thin"
                >
                  {field.label}
                </label>
              </div>
                ))}
                <div className="fixed bottom-0 left-0 w-full p-3 bg-pwip-white-100">
                  <button
                    type="submit"
                    className={`w-full text-white font-semibold py-4 px-4 rounded-md hover:bg-primary transition duration-300 ease-in-out shadow-md ${
                      (!formik.dirty || !formik.isValid || formik.isSubmitting) ? 'bg-gray-400 cursor-not-allowed' : 'bg-pwip-primary'
                    }`}
                    disabled={!formik.dirty || !formik.isValid || formik.isSubmitting}
                  >
                    Update Changes
                  </button>
                </div>
              </form>
         </div>
    </React.Fragment>
  );
}

export default withAuth(ProfileEdit)
