import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import withAuth from "@/hoc/withAuth";
import AppLayout from "@/layouts/appLayout.jsx";

// Import Components
import { Header } from "@/components/Header";

// Import Containers
import { riceAndBagsIcon } from "../../theme/icon";
// Import Layouts

function Learn() {
  const router = useRouter();

  const [mainContainerHeight, setMainContainerHeight] = React.useState(0);

  React.useEffect(() => {
    const element = document.getElementById("fixedMenuSection");
    if (element) {
      const height = element.offsetHeight;
      setMainContainerHeight(height);
    }
  }, []);

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />
        {/* <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        /> */}

        <title>Export Costing by pwip</title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Header />

        <div
          className={`relative top-[72px] h-full w-full bg-white z-10 py-6 px-5`}
        >
          <span className="text-pwip-gray-1000 font-sans font-bold text-lg text-left">
            Search Your Favorite Course
          </span>

          <input
            placeholder="Ex: Bullet rice"
            className="h-[48px] mt-[10px] w-full rounded-md border-[1px] border-pwip-gray-640 px-[18px] text-base font-sans"
          />

          <div className="w-full min-h-[136px] bg-pwip-gray-40 rounded-lg my-[20px]">
            {/*  */}
          </div>

          <div className="h-full w-full relative inline-flex flex-col space-y-5">
            <span className="text-pwip-gray-1000 font-sans font-bold text-lg text-left">
              Popular category
            </span>

            <div className="inline-flex items-center overflow-x-auto py-1 px-[1px] space-x-4">
              {["🔥 All", "🌾 Rice", "📦 Exports"].map((tag, tagIndex) => {
                return (
                  <div
                    key={tag + tagIndex}
                    className="relative inline-flex items-center justify-center space-x-4 border-[1.5px] border-pwip-primary px-4 py-1 rounded-full"
                  >
                    <span
                      id=""
                      className="w-auto text-pwip-primary font-sans font-normal text-sm select-none inherit"
                    >
                      {tag}
                    </span>
                  </div>
                );
              })}
            </div>

            <div className="inline-flex flex-col w-full">
              <div className="border-[1px] border-pwip-gray-650 rounded-lg p-2">
                {/*  */}
              </div>
            </div>
          </div>
        </div>
        {/*  */}
      </AppLayout>
    </React.Fragment>
  );
}

export default withAuth(Learn);
