export const FETCH_CONTAINERS_REQUEST = "FETCH_CONTAINERS_REQUEST";
export const FETCH_CONTAINERS_SUCCESS = "FETCH_CONTAINERS_SUCCESS";
export const FETCH_CONTAINERS_FAILURE = "FETCH_CONTAINERS_FAILURE";
