export const SET_COSTING_SELECTION = "SET_COSTING_SELECTION";
export const RESET_COSTING_SELECTION = "RESET_COSTING_SELECTION";
export const SET_COSTING_SELECTION_SUCCESS = "SET_COSTING_SELECTION_SUCCESS";
export const RESET_COSTING_SELECTION_SUCCESS =
  "RESET_COSTING_SELECTION_SUCCESS";

// generate quick costing
export const GENERATE_COSTING_REQUEST = "GENERATE_COSTING_REQUEST";
export const GENERATE_COSTING_SUCESS = "GENERATE_COSTING_SUCESS";
export const GENERATE_COSTING_FAILURE = "GENERATE_COSTING_FAILURE";

// generate custom costing
export const SET_CUSTOM_COSTING_SELECTION_REQUEST =
  "SET_CUSTOM_COSTING_SELECTION_REQUEST";
export const RESET_CUSTOM_COSTING_SELECTION_REQUEST =
  "SET_CUSTOM_COSTING_SELECTION_REQUEST";
export const SET_CUSTOM_COSTING_SELECTION_SUCCESS =
  "SET_CUSTOM_COSTING_SELECTION_SUCCESS";
export const SET_CUSTOM_COSTING_SELECTION_FAILURE =
  "SET_CUSTOM_COSTING_SELECTION_FAILURE";
