export const SET_COSTING_SELECTION = "SET_COSTING_SELECTION";
export const RESET_COSTING_SELECTION = "RESET_COSTING_SELECTION";
export const SET_COSTING_SELECTION_SUCCESS = "SET_COSTING_SELECTION_SUCCESS";
export const SET_COSTING_SELECTION_FAILURE = "SET_COSTING_SELECTION_FAILURE";
