export const SET_COSTING_SELECTION = "SET_COSTING_SELECTION";
export const RESET_COSTING_SELECTION = "RESET_COSTING_SELECTION";
export const SET_COSTING_SELECTION_SUCCESS = "SET_COSTING_SELECTION_SUCCESS";
export const RESET_COSTING_SELECTION_SUCCESS =
  "RESET_COSTING_SELECTION_SUCCESS";

// generate costing
export const GENERATE_COSTING_REQUEST = "GENERATE_COSTING_REQUEST";
export const GENERATE_COSTING_SUCESS = "GENERATE_COSTING_SUCESS";
export const GENERATE_COSTING_FAILURE = "GENERATE_COSTING_FAILURE";
