export const FETCH_LEARN_LIST_REQUEST = "FETCH_LEARN_LIST_REQUEST";
export const SET_LEARN_LIST_SUCCESS = "SET_LEARN_LIST_SUCCESS";
export const SET_LEARN_LIST_FAILURE = "SET_LEARN_LIST_FAILURE";

export const SET_LEARN_DETAILS_ID_REQUEST = "SET_LEARN_DETAILS_ID_REQUEST";
export const SET_LEARN_DETAILS_ID_SUCCESS = "SET_LEARN_DETAILS_ID_SUCCESS";
export const SET_LEARN_DETAILS_ID_FAILURE = "SET_LEARN_DETAILS_ID_FAILURE";

export const SET_LEARN_DETAILS_REQUEST = "SET_LEARN_DETAILS_REQUEST";
export const SET_LEARN_DETAILS_SUCCESS = "SET_LEARN_DETAILS_SUCCESS";
export const SET_LEARN_DETAILS_FAILURE = "SET_LEARN_DETAILS_FAILURE";
