export const FETCH_LOCATION_DESTINATION_REQUEST =
  "FETCH_LOCATION_DESTINATION_REQUEST";
export const FETCH_LOCATION_DESTINATION_SUCCESS =
  "FETCH_LOCATION_DESTINATION_SUCCESS";
export const FETCH_LOCATION_DESTINATION_FAILURE =
  "FETCH_LOCATION_DESTINATION_FAILURE";
