// save quick costing
export const SAVE_COSTING_REQUEST = "SAVE_COSTING_REQUEST";
export const SAVE_COSTING_SUCCESS = "SAVE_COSTING_SUCCESS";
export const SAVE_COSTING_FAILURE = "SAVE_COSTING_FAILURE";

// update quick costing
export const UPDATE_COSTING_REQUEST = "UPDATE_COSTING_REQUEST";
export const UPDATE_COSTING_SUCCESS = "UPDATE_COSTING_SUCCESS";
export const UPDATE_COSTING_FAILURE = "UPDATE_COSTING_FAILURE";

// get my costing
export const FETCH_MY_COSTING_REQUEST = "FETCH_MY_COSTING_REQUEST";
export const FETCH_MY_COSTING_SUCCESS = "FETCH_MY_COSTING_SUCCESS";
export const FETCH_MY_COSTING_FAILURE = "FETCH_MY_COSTING_FAILURE";

// get my costing
export const FETCH_ALL_MY_COSTINGS_REQUEST = "FETCH_ALL_MY_COSTINGS_REQUEST";
export const FETCH_ALL_MY_COSTINGS_SUCCESS = "FETCH_ALL_MY_COSTINGS_SUCCESS";
export const FETCH_ALL_MY_COSTINGS_FAILURE = "FETCH_ALL_MY_COSTINGS_FAILURE";
