// POL
export const SET_SELECTED_POL_FOR_OFC_REQUEST =
  "SET_SELECTED_POL_FOR_OFC_REQUEST";
export const SET_SELECTED_POL_FOR_OFC_SUCCESS =
  "SET_SELECTED_POL_FOR_OFC_SUCCESS";
export const SET_SELECTED_POL_FOR_OFC_FAILURE =
  "SET_SELECTED_POL_FOR_OFC_FAILURE";

// POD
export const SET_SELECTED_POD_FOR_OFC_REQUEST =
  "SET_SELECTED_POD_FOR_OFC_REQUEST";
export const SET_SELECTED_POD_FOR_OFC_SUCCESS =
  "SET_SELECTED_POD_FOR_OFC_SUCCESS";
export const SET_SELECTED_POD_FOR_OFC_FAILURE =
  "SET_SELECTED_POD_FOR_OFC_FAILURE";
