export const FETCH_PACKAGE_BAGS_REQUEST = "FETCH_PACKAGE_BAGS_REQUEST";
export const FETCH_PACKAGE_BAGS_SUCCESS = "FETCH_PACKAGE_BAGS_SUCCESS";
export const FETCH_PACKAGE_BAGS_FAILURE = "FETCH_PACKAGE_BAGS_FAILURE";
