export const SET_PREVIEW_DATA_REQUEST = "SET_PREVIEW_DATA_REQUEST";
export const SET_PREVIEW_DATA_SUCCESS = "SET_PREVIEW_DATA_SUCCESS";
export const SET_PREVIEW_DATA_FAILURE = "SET_PREVIEW_DATA_FAILURE";
