export const SET_TERMS_OF_SHIPMENT_REQUEST = "SET_TERMS_OF_SHIPMENT_REQUEST";
export const SET_TERMS_OF_SHIPMENT_SUCCESS = "SET_TERMS_OF_SHIPMENT_SUCCESS";
export const SET_TERMS_OF_SHIPMENT_FAILURE = "SET_TERMS_OF_SHIPMENT_FAILURE";
