export const TOAST_NOTIFICATION_REQUEST = "TOAST_NOTIFICATION_REQUEST";
export const SHOW_TOAST_NOTIFICATION_SUCCESS =
  "SHOW_TOAST_NOTIFICATION_SUCCESS";
export const HIDE_TOAST_NOTIFICATION_FAILURE =
  "HIDE_TOAST_NOTIFICATION_FAILURE";
