// loader
export const SHOW_LOADER_REQUEST = "SHOW_LOADER_REQUEST";
export const SHOW_LOADER_SUCCESS = "SHOW_LOADER_SUCCESS";
export const SHOW_LOADER_FAILURE = "SHOW_LOADER_FAILURE";

// forexRate
export const SET_FOREX_RATE_REQUEST = "SET_FOREX_RATE_REQUEST";
export const SET_FOREX_RATE_SUCCESS = "SET_FOREX_RATE_SUCCESS";
export const SET_FOREX_RATE_FAILURE = "SET_FOREX_RATE_FAILURE";
