// loader
export const SHOW_LOADER_REQUEST = "SHOW_LOADER_REQUEST";
export const SHOW_LOADER_SUCCESS = "SHOW_LOADER_SUCCESS";
export const SHOW_LOADER_FAILURE = "SHOW_LOADER_FAILURE";

// forexRate
export const SET_FOREX_RATE_REQUEST = "SET_FOREX_RATE_REQUEST";
export const SET_FOREX_RATE_SUCCESS = "SET_FOREX_RATE_SUCCESS";
export const SET_FOREX_RATE_FAILURE = "SET_FOREX_RATE_FAILURE";

// search
export const SET_SEARCH_SCREEN_REQUEST = "SET_SEARCH_SCREEN_REQUEST";
export const SET_SEARCH_SCREEN_SUCCESS = "SET_SEARCH_SCREEN_SUCCESS";
export const SET_SEARCH_SCREEN_FAILURE = "SET_SEARCH_SCREEN_FAILURE";

// Send OTP and verify
export const SET_OTP_SEND_REQUEST = "SET_OTP_SEND_REQUEST";
export const SET_OTP_RECEIVED_SUCCESS = "SET_OTP_RECEIVED_SUCCESS";
export const SET_OTP_RECEIVED_FAILURE = "SET_OTP_RECEIVED_FAILURE";
