export const FETCH_VARIANT_PRICE_REQUEST = "FETCH_VARIANT_PRICE_REQUEST";
export const FETCH_VARIANT_PRICE_SUCCESS = "FETCH_VARIANT_PRICE_SUCCESS";
export const FETCH_VARIANT_PRICE_FAILURE = "FETCH_VARIANT_PRICE_FAILURE";
