export const FETCH_VARIANT_PRICE_REQUEST = "FETCH_VARIANT_PRICE_REQUEST";
export const FETCH_VARIANT_PRICE_SUCCESS = "FETCH_VARIANT_PRICE_SUCCESS";
export const FETCH_VARIANT_PRICE_FAILURE = "FETCH_VARIANT_PRICE_FAILURE";

// WATCHLIST
export const FETCH_WATCHLIST_FOR_VARIANT_REQUEST =
  "FETCH_WATCHLIST_FOR_VARIANT_REQUEST";
export const ADD_REMOVE_VARIANT_IN_WATCHLIST_REQUEST =
  "ADD_REMOVE_VARIANT_IN_WATCHLIST_REQUEST";
export const VARIANTS_WATCHLIST_SUCCESS = "VARIANTS_WATCHLIST_SUCCESS";
export const VARIANTS_WATCHLIST_FAILURE = "VARIANTS_WATCHLIST_FAILURE";
