export const FETCH_VARIANT_PROFILE_REQUEST = "FETCH_VARIANT_PROFILE_REQUEST";
export const SET_VARIANT_PROFILE_SUCCESS = "SET_VARIANT_PROFILE_SUCCESS";
export const SET_VARIANT_PROFILE_FAILURE = "SET_VARIANT_PROFILE_FAILURE";
