import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import withAuth from "@/hoc/withAuth";
import AppLayout from "@/layouts/appLayout.jsx";

// Import Components
import { Header } from "@/components/Header";

// Import Containers

// Import Layouts

function More() {
  const router = useRouter();

  const [mainContainerHeight, setMainContainerHeight] = React.useState(0);

  React.useEffect(() => {
    const element = document.getElementById("fixedMenuSection");
    if (element) {
      const height = element.offsetHeight;
      setMainContainerHeight(height);
    }
  }, []);

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />

        <title>Export Costing by pwip</title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Header />

        <div
          className={`relative top-[72px] h-full w-full bg-white z-10 py-6 px-5`}
        >
          <div
            id="fixedMenuSection"
            className={`fixed left-0 top-[72px] h-[auto] w-full bg-pwip-primary z-0 py-3 px-5`}
          >
            <input
              placeholder="Search previous costing"
              className="h-[48px] w-full rounded-md bg-pwip-primary-100 px-[18px] text-base font-sans"
            />
          </div>
          <div
            className={`min-h-[calc(100vh-196px)] inline-flex flex-col space-y-3 h-full w-full bg-white pb-0 overflow-auto hide-scroll-bar`}
            style={{
              paddingTop: mainContainerHeight - 20 + "px",
              paddingBottom: mainContainerHeight + 20 + "px",
            }}
          >
            {/*  */}
          </div>
        </div>
        {/*  */}
      </AppLayout>
    </React.Fragment>
  );
}

export default withAuth(More);
