import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import withAuth from "@/hoc/withAuth";
import AppLayout from "@/layouts/appLayout.jsx";

// Import Components
import { Header } from "@/components/Header";

// Import Containers
import { riceAndBagsIcon } from "../../theme/icon";
// Import Layouts

function getMobileOperatingSystem() {
  var userAgent = navigator.userAgent || navigator.vendor || window.opera;

  // Windows Phone must come first because its UA also contains "Android"
  if (/windows phone/i.test(userAgent)) {
    return "windows";
  }

  if (/android/i.test(userAgent)) {
    return "android";
  }

  // iOS detection from: http://stackoverflow.com/a/9039885/177710
  if (/iPad|iPhone|iPod/.test(userAgent) && !window.MSStream) {
    return "ios";
  }

  return "unknown";
}

function Community() {
  const router = useRouter();
  const [devicePlatform, setDevicePlatform] = useState(null);

  useEffect(() => {
    const platform = getMobileOperatingSystem();

    setDevicePlatform(platform);
  }, []);

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />

        <title>Community | PWIP</title>

        <meta name="PWIP Exports" content="PWIP Exports" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/*<meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
*/}
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />

        {/* <link rel="manifest" href="/manifest.json" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="h-auto w-full">
        <div
          className="fixed bottom-[15rem] right-0 bg-pwip-primary text-white text-sm font-sans pl-3 pr-2 py-2 rounded-l-full inline-flex items-center justify-center z-[999]"
          style={{ boxShadow: "6px 4px 12px 1px #14517b60" }}
          onClick={() => {
            router.push("/export-costing");
          }}
        >
          <span>Return to app</span>
        </div>
        <iframe
          className="fixed top-0 left-0 z-0"
          style={{
            border: 0,
            boxShadow: "none",
            width: "100%",
            height: devicePlatform === "ios" ? "calc(100vh - 108px)" : "100vh",
          }}
          src="https://community.pwip.co?frame=true"
        ></iframe>
      </div>
    </React.Fragment>
  );
}

export default withAuth(Community);
