import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import withAuth from "@/hoc/withAuth";
import AppLayout from "@/layouts/appLayout.jsx";

// Import Components
import { Header } from "@/components/Header";

// Import Containers
import { riceAndBagsIcon } from "../../theme/icon";
// Import Layouts

function Community() {
  const router = useRouter();

  //   useEffect(() => {
  //     const iframes = Array.from(document.getElementsByTagName("iframe"));

  //     iframes.forEach((iframe) => {
  //       iframe?.contentWindow?.addEventListener(
  //         "load",
  //         () => {
  //           const doc = iframe.contentWindow.document;
  //           iframe.height = doc.body.scrollHeight;
  //         },
  //         true
  //       );
  //       iframe?.contentWindow?.addEventListener(
  //         "resize",
  //         () => {
  //           iframe.height = iframe.contentWindow.document.body.scrollHeight + 40;
  //         },
  //         true
  //       );
  //     });

  //     return () => {
  //       iframes.forEach((iframe) => {
  //         iframe?.contentWindow?.removeEventListener(
  //           "load",
  //           () => {
  //             const doc = iframe.contentWindow.document;
  //             iframe.height = doc.body.scrollHeight;
  //           },
  //           true
  //         );
  //         iframe?.contentWindow?.removeEventListener(
  //           "resize",
  //           () => {
  //             iframe.height =
  //               iframe.contentWindow.document.body.scrollHeight + 40;
  //           },
  //           true
  //         );
  //       });
  //     };
  //   }, []);

  return (
    <React.Fragment>
      <Head>
        <meta charSet="utf-8" />

        <title>Export Costing by pwip</title>

        <meta name="Reciplay" content="Reciplay" />
        <meta name="description" content="Generated by create next app" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full w-full relative">
        <iframe
          style={{
            border: 0,
            boxShadow: "none",
            width: "100%",
            height: "100vh",
            position: "relative",
            zIndex: 0,
          }}
          src="https://community.pwip.co?frame=true"
          onLoadedData={() => {
            router.back();
          }}
        ></iframe>

        <div
          className="absolute bottom-[8rem] right-0 bg-pwip-primary text-white text-sm font-sans pl-3 pr-2 py-2 rounded-l-full inline-flex items-center justify-center"
          style={{ boxShadow: "6px 4px 12px 1px #14517b60" }}
          onClick={() => {
            router.back();
          }}
        >
          <span>Return to app</span>
        </div>
      </div>
    </React.Fragment>
  );
}

export default withAuth(Community);
